export interface EthTx {
    "blockNumber": string,
    "timeStamp": string,
    "hash": string,
    "nonce": string,
    "blockHash": string,
    "transactionIndex": string,
    "from": string,
    "to": string,
    "value": string,
    "gas": string,
    "gasPrice": string,
    "isError": string,
    "confirmations": string,
}